/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PremiumPaymentRouteImport } from './routes/premium-payment'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BikesRouteImport } from './routes/bikes'
import { Route as AdminPortalRouteImport } from './routes/admin-portal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BikesIndexRouteImport } from './routes/bikes.index'
import { Route as PolicyBookingIdRouteImport } from './routes/policy.$bookingId'
import { Route as PaymentBookingIdRouteImport } from './routes/payment.$bookingId'
import { Route as InvoiceBookingIdRouteImport } from './routes/invoice.$bookingId'
import { Route as ConfirmationBookingIdRouteImport } from './routes/confirmation.$bookingId'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as BookingStatusRouteImport } from './routes/booking.status'
import { Route as BookingFailedRouteImport } from './routes/booking.failed'
import { Route as BookingBikeIdRouteImport } from './routes/booking.$bikeId'
import { Route as BikesBikeIdRouteImport } from './routes/bikes.$bikeId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumPaymentRoute = PremiumPaymentRouteImport.update({
  id: '/premium-payment',
  path: '/premium-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesRoute = BikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/admin-portal',
  path: '/admin-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIndexRoute = BikesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BikesRoute,
} as any)
const PolicyBookingIdRoute = PolicyBookingIdRouteImport.update({
  id: '/policy/$bookingId',
  path: '/policy/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentBookingIdRoute = PaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceBookingIdRoute = InvoiceBookingIdRouteImport.update({
  id: '/invoice/$bookingId',
  path: '/invoice/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationBookingIdRoute = ConfirmationBookingIdRouteImport.update({
  id: '/confirmation/$bookingId',
  path: '/confirmation/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusRoute = BookingStatusRouteImport.update({
  id: '/booking/status',
  path: '/booking/status',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFailedRoute = BookingFailedRouteImport.update({
  id: '/booking/failed',
  path: '/booking/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBikeIdRoute = BookingBikeIdRouteImport.update({
  id: '/booking/$bikeId',
  path: '/booking/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesBikeIdRoute = BikesBikeIdRouteImport.update({
  id: '/$bikeId',
  path: '/$bikeId',
  getParentRoute: () => BikesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/bikes': typeof BikesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/premium': typeof PremiumRoute
  '/premium-payment': typeof PremiumPaymentRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
  '/booking/$bikeId': typeof BookingBikeIdRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/status': typeof BookingStatusRoute
  '/booking/success': typeof BookingSuccessRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/policy/$bookingId': typeof PolicyBookingIdRoute
  '/bikes/': typeof BikesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/premium': typeof PremiumRoute
  '/premium-payment': typeof PremiumPaymentRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
  '/booking/$bikeId': typeof BookingBikeIdRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/status': typeof BookingStatusRoute
  '/booking/success': typeof BookingSuccessRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/policy/$bookingId': typeof PolicyBookingIdRoute
  '/bikes': typeof BikesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-portal': typeof AdminPortalRoute
  '/bikes': typeof BikesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/premium': typeof PremiumRoute
  '/premium-payment': typeof PremiumPaymentRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/bikes/$bikeId': typeof BikesBikeIdRoute
  '/booking/$bikeId': typeof BookingBikeIdRoute
  '/booking/failed': typeof BookingFailedRoute
  '/booking/status': typeof BookingStatusRoute
  '/booking/success': typeof BookingSuccessRoute
  '/confirmation/$bookingId': typeof ConfirmationBookingIdRoute
  '/invoice/$bookingId': typeof InvoiceBookingIdRoute
  '/payment/$bookingId': typeof PaymentBookingIdRoute
  '/policy/$bookingId': typeof PolicyBookingIdRoute
  '/bikes/': typeof BikesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-portal'
    | '/bikes'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment-failed'
    | '/premium'
    | '/premium-payment'
    | '/signup'
    | '/auth/callback'
    | '/bikes/$bikeId'
    | '/booking/$bikeId'
    | '/booking/failed'
    | '/booking/status'
    | '/booking/success'
    | '/confirmation/$bookingId'
    | '/invoice/$bookingId'
    | '/payment/$bookingId'
    | '/policy/$bookingId'
    | '/bikes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-portal'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment-failed'
    | '/premium'
    | '/premium-payment'
    | '/signup'
    | '/auth/callback'
    | '/bikes/$bikeId'
    | '/booking/$bikeId'
    | '/booking/failed'
    | '/booking/status'
    | '/booking/success'
    | '/confirmation/$bookingId'
    | '/invoice/$bookingId'
    | '/payment/$bookingId'
    | '/policy/$bookingId'
    | '/bikes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-portal'
    | '/bikes'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/payment-failed'
    | '/premium'
    | '/premium-payment'
    | '/signup'
    | '/auth/callback'
    | '/bikes/$bikeId'
    | '/booking/$bikeId'
    | '/booking/failed'
    | '/booking/status'
    | '/booking/success'
    | '/confirmation/$bookingId'
    | '/invoice/$bookingId'
    | '/payment/$bookingId'
    | '/policy/$bookingId'
    | '/bikes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminPortalRoute: typeof AdminPortalRoute
  BikesRoute: typeof BikesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PremiumRoute: typeof PremiumRoute
  PremiumPaymentRoute: typeof PremiumPaymentRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookingBikeIdRoute: typeof BookingBikeIdRoute
  BookingFailedRoute: typeof BookingFailedRoute
  BookingStatusRoute: typeof BookingStatusRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ConfirmationBookingIdRoute: typeof ConfirmationBookingIdRoute
  InvoiceBookingIdRoute: typeof InvoiceBookingIdRoute
  PaymentBookingIdRoute: typeof PaymentBookingIdRoute
  PolicyBookingIdRoute: typeof PolicyBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-payment': {
      id: '/premium-payment'
      path: '/premium-payment'
      fullPath: '/premium-payment'
      preLoaderRoute: typeof PremiumPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes': {
      id: '/bikes'
      path: '/bikes'
      fullPath: '/bikes'
      preLoaderRoute: typeof BikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-portal': {
      id: '/admin-portal'
      path: '/admin-portal'
      fullPath: '/admin-portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/': {
      id: '/bikes/'
      path: '/'
      fullPath: '/bikes/'
      preLoaderRoute: typeof BikesIndexRouteImport
      parentRoute: typeof BikesRoute
    }
    '/policy/$bookingId': {
      id: '/policy/$bookingId'
      path: '/policy/$bookingId'
      fullPath: '/policy/$bookingId'
      preLoaderRoute: typeof PolicyBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$bookingId': {
      id: '/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PaymentBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$bookingId': {
      id: '/invoice/$bookingId'
      path: '/invoice/$bookingId'
      fullPath: '/invoice/$bookingId'
      preLoaderRoute: typeof InvoiceBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$bookingId': {
      id: '/confirmation/$bookingId'
      path: '/confirmation/$bookingId'
      fullPath: '/confirmation/$bookingId'
      preLoaderRoute: typeof ConfirmationBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/status': {
      id: '/booking/status'
      path: '/booking/status'
      fullPath: '/booking/status'
      preLoaderRoute: typeof BookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/failed': {
      id: '/booking/failed'
      path: '/booking/failed'
      fullPath: '/booking/failed'
      preLoaderRoute: typeof BookingFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bikeId': {
      id: '/booking/$bikeId'
      path: '/booking/$bikeId'
      fullPath: '/booking/$bikeId'
      preLoaderRoute: typeof BookingBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$bikeId': {
      id: '/bikes/$bikeId'
      path: '/$bikeId'
      fullPath: '/bikes/$bikeId'
      preLoaderRoute: typeof BikesBikeIdRouteImport
      parentRoute: typeof BikesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BikesRouteChildren {
  BikesBikeIdRoute: typeof BikesBikeIdRoute
  BikesIndexRoute: typeof BikesIndexRoute
}

const BikesRouteChildren: BikesRouteChildren = {
  BikesBikeIdRoute: BikesBikeIdRoute,
  BikesIndexRoute: BikesIndexRoute,
}

const BikesRouteWithChildren = BikesRoute._addFileChildren(BikesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminPortalRoute: AdminPortalRoute,
  BikesRoute: BikesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PremiumRoute: PremiumRoute,
  PremiumPaymentRoute: PremiumPaymentRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookingBikeIdRoute: BookingBikeIdRoute,
  BookingFailedRoute: BookingFailedRoute,
  BookingStatusRoute: BookingStatusRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ConfirmationBookingIdRoute: ConfirmationBookingIdRoute,
  InvoiceBookingIdRoute: InvoiceBookingIdRoute,
  PaymentBookingIdRoute: PaymentBookingIdRoute,
  PolicyBookingIdRoute: PolicyBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
